### ISSUE TITLE
Compatibility with Prettier 3

### ISSUE THREAD

**Issue by ioanlucut** [siefkenj/prettier-plugin-latex#2]
Hello!

I noticed that this plugin does not work with Prettier@3.

The error I get is:

```
InvalidDocError: Unexpected doc.type 'concat'.
```

**Comment by siefkenj** [comment]
Okay. `v1.0.1` has been released and should have Prettier v3 support! Let me know if it works out :-)

Fixed via #3 #4

**Comment by ioanlucut** [comment]
@siefkenj I am definitively impressed by how fast was this tackled.
Thanks a lot!

Indeed, it works. Just a tiny issue: Shouldn't be version `2.0.1`?

**Comment by siefkenj** [comment]
Yes, you're right. `v2.0.1` is the one I released last night ;-)

**Comment by ioanlucut** [comment]
Could you be so nice to republish under `2.0.1`?

( see https://www.npmjs.com/package/prettier-plugin-latex?activeTab=versions )

**Comment by siefkenj** [comment]
Oops. What a mistake! I will republish as `2.0.1` in 10 days.

**Comment by ioanlucut** [comment]
Thanks a ton.

**Comment by siefkenj** [comment]
Done!
